package ga.scmc.client.renderer;

import ga.scmc.lib.Library;

public class Resources {

	public static final String BROODLING_BASE 					= Library.RL_BASE + "textures/entity/broodling_base.png";
	public static final String BROODLING_OVERLAY				= Library.RL_BASE + "textures/entity/broodling_overlay.png";
	public static final String BRUTALISK_BASE 					= Library.RL_BASE + "textures/entity/brutalisk_base.png";
	public static final String BRUTALISK_OVERLAY 				= Library.RL_BASE + "textures/entity/brutalisk_overlay.png";
	public static final String BULLET_C14 						= Library.RL_BASE + "textures/entity/bullet.png";
	public static final String CIVILIAN 						= Library.RL_BASE + "textures/entity/civilian.png";
	public static final String DARKPROBE_BASE 					= Library.RL_BASE + "textures/entity/darkprobe_base.png";
	public static final String DARKPROBE_GLOW_DYNAMIC 			= Library.RL_BASE + "textures/entity/darkprobe_glow_dynamic.png";
	public static final String DARKPROBE_OVERLAY 				= Library.RL_BASE + "textures/entity/darkprobe_overlay.png";
	public static final String DARKTEMPLAR_BASE 				= Library.RL_BASE + "textures/entity/darktemplar_base.png";
	public static final String DARKTEMPLAR_GLOW_STATIC 			= Library.RL_BASE + "textures/entity/darktemplar_glow_static.png";
	public static final String DARKTEMPLAR_OVERLAY				= Library.RL_BASE + "textures/entity/darktemplar_overlay.png";
	public static final String HYDRALISK_BASE 					= Library.RL_BASE + "textures/entity/hydralisk_base.png";
	public static final String HYDRALISK_GLOW_STATIC 			= Library.RL_BASE + "textures/entity/hydralisk_glow_static.png";
	public static final String HYDRALISK_OVERLAY 				= Library.RL_BASE + "textures/entity/hydralisk_overlay.png";
	public static final String HYDRALISK_SPIKE	 				= Library.RL_BASE + "textures/entity/hydraliskspike.png";
	public static final String INFESTED_CIVILIAN 				= Library.RL_BASE + "textures/entity/infestedcivilian.png";
	public static final String KAKARU			 				= Library.RL_BASE + "textures/entity/kakaru.png";
	public static final String LARVA_BASE		 				= Library.RL_BASE + "textures/entity/larva_base.png";
	public static final String LARVA_GLOW_STATIC 				= Library.RL_BASE + "textures/entity/larva_glow_static.png";
	public static final String LARVA_OVERLAY	 				= Library.RL_BASE + "textures/entity/larva_overlay.png";
	public static final String LARVA_COCOON_BASE 				= Library.RL_BASE + "textures/entity/larvacocoon_base.png";
	public static final String LARVA_COCOON_OVERLAY				= Library.RL_BASE + "textures/entity/larvacocoon_overlay.png";
	public static final String PREAVER_BASE		 				= Library.RL_BASE + "textures/entity/preaver_base.png";
	public static final String PREAVER_GLOW_DYNAMIC				= Library.RL_BASE + "textures/entity/preaver_glow_dynamic.png";
	public static final String PREAVER_OVERLAY 					= Library.RL_BASE + "textures/entity/preaver_overlay.png";
	public static final String PREDATOR_BASE 					= Library.RL_BASE + "textures/entity/predator_base.png";
	public static final String PREDATOR_GLOW_DYNAMIC 			= Library.RL_BASE + "textures/entity/predator_glow_dynamic.png";
	public static final String PREDATOR_GLOW_STATIC 			= Library.RL_BASE + "textures/entity/predator_glow_static.png";
	public static final String PREDATOR_OVERLAY 				= Library.RL_BASE + "textures/entity/predator_overlay.png";
	public static final String PROBE_BASE		 				= Library.RL_BASE + "textures/entity/probe_base.png";
	public static final String PROBE_GLOW_DYNAMIC 				= Library.RL_BASE + "textures/entity/probe_glow_dynamic.png";
	public static final String PROBE_OVERLAY	 				= Library.RL_BASE + "textures/entity/probe_overlay.png";
	public static final String SCARAB_LAYER		 				= Library.RL_BASE + "textures/entity/scarab_layer.png";
	public static final String SCARAB 							= Library.RL_BASE + "textures/entity/scarab.png";
	public static final String TASTELOPE_BASE 					= Library.RL_BASE + "textures/entity/tastelope_base.png";
	public static final String TASTELOPE_GLOW_STATIC 			= Library.RL_BASE + "textures/entity/tastelope_glow_static.png";
	public static final String VOID_PROBE_BASE 					= Library.RL_BASE + "textures/entity/voidprobe_base.png";
	public static final String VOID_PROBE_GLOW_DYNAMIC			= Library.RL_BASE + "textures/entity/voidprobe_glow_dynamic.png";
	public static final String VOID_PROBE_OVERLAY 				= Library.RL_BASE + "textures/entity/voidprobe_overlay.png";
	public static final String ZEALOT_BASE 						= Library.RL_BASE + "textures/entity/zealot_base.png";
	public static final String ZEALOT_GLOW_DYNAMIC 				= Library.RL_BASE + "textures/entity/zealot_glow_dynamic.png";
	public static final String ZEALOT_GLOW_STATIC 				= Library.RL_BASE + "textures/entity/zealot_glow_static.png";
	public static final String ZEALOT_OVERLAY 					= Library.RL_BASE + "textures/entity/zealot_overlay.png";
	public static final String ZERGLING_BASE 					= Library.RL_BASE + "textures/entity/zergling_base.png";
	public static final String ZERGLING_GLOW_STATIC 			= Library.RL_BASE + "textures/entity/zergling_glow_static.png";
	public static final String ZERGLING_OVERLAY 				= Library.RL_BASE + "textures/entity/zergling_overlay.png";
	public static final String ZERGLINGBOOST_BASE 				= Library.RL_BASE + "textures/entity/zerglingboost_base.png";
	public static final String ZERGLINGRAPTOR_BASE 				= Library.RL_BASE + "textures/entity/zerglingraptor_base.png";
	public static final String ZERGLINGSWARMLING_BASE 			= Library.RL_BASE + "textures/entity/zerglingswarmling_base.png";
	public static final String ZERGLINGSWARMLING_GLOW_STATIC 	= Library.RL_BASE + "textures/entity/zerglingswarmling_glow_static.png";
	public static final String MARINE_BASE                      = Library.RL_BASE + "textures/entity/marine/marine_base.png";
	public static final String MARINE_OVERLAY                   = Library.RL_BASE + "textures/entity/marine/marine_overlay.png";
}
