package com.hypeirochus.scmc.worldgen.structure;

import java.util.Random;

import com.hypeirochus.scmc.handlers.BlockHandler;
import com.hypeirochus.scmc.handlers.LootTableHandler;
import com.hypeirochus.scmc.lib.IObjectParsable;

import net.minecraft.block.Block;
import net.minecraft.block.material.Material;
import net.minecraft.init.Blocks;
import net.minecraft.tileentity.TileEntityChest;
import net.minecraft.util.math.BlockPos;
import net.minecraft.world.World;
import net.minecraft.world.gen.structure.WoodlandMansionPieces.MansionTemplate;
import net.minecraft.world.gen.structure.template.Template;

public class StructureTerranBunkerTemplate extends SCWorldGenerator implements INBTStructure, IObjectParsable {

	public static final String STRUCTURE_NAME = "terran.bunker";
		
	private boolean checkSpawnPosition;

	public StructureTerranBunkerTemplate() {
		this.checkSpawnPosition = false;
	}
	
	@Override
	public boolean generate(World world, BlockPos pos) {
		if (this.checkSpawnPosition) {
			if (!LocationIsValidSpawn(world, pos) || !LocationIsValidSpawn(world, pos.add(17, 0, 0)) || !LocationIsValidSpawn(world, pos.add(17, 0, 15)) || !LocationIsValidSpawn(world, pos.add(0, 0, 15))) {
				return false;
			}
		}
		
		Template template = this.getTemplate(world, STRUCTURE_NAME);
		if (template != null) {
			placeStructure(template, world, pos, this.getDefaultPlacementSettings());
			return true;
		}
		return false;
	}

	@Override
	public void setFlags(Object[] flags) {
		if (flags.length > 0) {
			checkSpawnPosition = this.parseBoolean(flags[0]);
		}
	}

	@Override
	public void onParseFail(byte parseType, Exception e) {
		if(parseType == BOOLEAN) {
			checkSpawnPosition = false;
		}
	}

	@Override
	public boolean generate(World world, Random rand, int offsetX, int offsetY, int offsetZ, BlockPos pos, boolean flag) {
		generate_r0(world, pos, this.checkSpawnPosition);
		return true;
	}

	public boolean generate_r0(World worldIn, BlockPos bp, boolean flag) {
		if (flag) {
			if (!LocationIsValidSpawn(worldIn, bp) || !LocationIsValidSpawn(worldIn, bp.add(17, 0, 0)) || !LocationIsValidSpawn(worldIn, bp.add(17, 0, 15)) || !LocationIsValidSpawn(worldIn, bp.add(0, 0, 15))) {
				return false;
			}
		}
		int k = 0;
		int i = 0;
		int j = 0;
		worldIn.setBlockState(bp.add(i + 0, j + 0, k + 7), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 0, j + 0, k + 8), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 0, j + 1, k + 7), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 0, j + 1, k + 8), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 0, j + 2, k + 6), BlockHandler.PARISTEEL_METAL.getStateFromMeta(15));
		worldIn.setBlockState(bp.add(i + 0, j + 2, k + 9), BlockHandler.PARISTEEL_METAL.getStateFromMeta(15));
		worldIn.setBlockState(bp.add(i + 0, j + 3, k + 6), BlockHandler.PARISTEEL_METAL.getStateFromMeta(15));
		worldIn.setBlockState(bp.add(i + 0, j + 3, k + 9), BlockHandler.PARISTEEL_METAL.getStateFromMeta(15));
		worldIn.setBlockState(bp.add(i + 1, j + 0, k + 7), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 1, j + 0, k + 8), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 1, j + 1, k + 6), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 1, j + 1, k + 9), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 1, j + 2, k + 6), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 1, j + 2, k + 9), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 1, j + 3, k + 6), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 1, j + 3, k + 9), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 1, j + 4, k + 6), BlockHandler.PARISTEEL_METAL.getStateFromMeta(15));
		worldIn.setBlockState(bp.add(i + 1, j + 4, k + 9), BlockHandler.PARISTEEL_METAL.getStateFromMeta(15));
		worldIn.setBlockState(bp.add(i + 2, j + 0, k + 7), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 2, j + 0, k + 8), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 2, j + 1, k + 6), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 2, j + 1, k + 9), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 2, j + 2, k + 6), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 2, j + 2, k + 9), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 2, j + 3, k + 6), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 2, j + 3, k + 9), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 2, j + 4, k + 6), BlockHandler.PARISTEEL_METAL.getStateFromMeta(15));
		worldIn.setBlockState(bp.add(i + 2, j + 4, k + 9), BlockHandler.PARISTEEL_METAL.getStateFromMeta(15));
		worldIn.setBlockState(bp.add(i + 3, j + 0, k + 6), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 3, j + 0, k + 7), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 3, j + 0, k + 8), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 3, j + 0, k + 9), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 3, j + 1, k + 3), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 3, j + 1, k + 4), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 3, j + 1, k + 5), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 3, j + 1, k + 10), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 3, j + 1, k + 11), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 3, j + 1, k + 12), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 3, j + 2, k + 2), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 3, j + 2, k + 3), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 3, j + 2, k + 4), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 3, j + 2, k + 5), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 3, j + 2, k + 10), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 3, j + 2, k + 11), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 3, j + 2, k + 12), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 3, j + 2, k + 13), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 3, j + 3, k + 2), BlockHandler.PARISTEEL_METAL.getStateFromMeta(3));
		worldIn.setBlockState(bp.add(i + 3, j + 3, k + 3), BlockHandler.PARISTEEL_METAL.getStateFromMeta(3));
		worldIn.setBlockState(bp.add(i + 3, j + 3, k + 4), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 3, j + 3, k + 5), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 3, j + 3, k + 10), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 3, j + 3, k + 11), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 3, j + 3, k + 12), BlockHandler.PARISTEEL_METAL.getStateFromMeta(3));
		worldIn.setBlockState(bp.add(i + 3, j + 3, k + 13), BlockHandler.PARISTEEL_METAL.getStateFromMeta(3));
		worldIn.setBlockState(bp.add(i + 3, j + 4, k + 3), BlockHandler.PARISTEEL_METAL.getStateFromMeta(3));
		worldIn.setBlockState(bp.add(i + 3, j + 4, k + 4), BlockHandler.PARISTEEL_METAL.getStateFromMeta(3));
		worldIn.setBlockState(bp.add(i + 3, j + 4, k + 5), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 3, j + 4, k + 6), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 3, j + 4, k + 7), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 3, j + 4, k + 8), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 3, j + 4, k + 9), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 3, j + 4, k + 10), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 3, j + 4, k + 11), BlockHandler.PARISTEEL_METAL.getStateFromMeta(3));
		worldIn.setBlockState(bp.add(i + 3, j + 4, k + 12), BlockHandler.PARISTEEL_METAL.getStateFromMeta(3));
		worldIn.setBlockState(bp.add(i + 3, j + 5, k + 6), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 3, j + 5, k + 7), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 3, j + 5, k + 8), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 3, j + 5, k + 9), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 4, j + 0, k + 3), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 4, j + 0, k + 4), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 4, j + 0, k + 5), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 4, j + 0, k + 6), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 4, j + 0, k + 7), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 4, j + 0, k + 8), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 4, j + 0, k + 9), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 4, j + 0, k + 10), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 4, j + 0, k + 11), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 4, j + 0, k + 12), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 4, j + 1, k + 2), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));

		setTileEntityBlock(worldIn, bp.add(i + 4, j + 1, k + 12), Blocks.CHEST.getDefaultState(), new TileEntityChest());
		setLockableLoot(worldIn, bp.add(i + 4, j + 1, k + 12), LootTableHandler.TERRAN_BUNKER);

		worldIn.setBlockState(bp.add(i + 4, j + 1, k + 13), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 4, j + 2, k + 2), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 4, j + 2, k + 13), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 4, j + 3, k + 2), BlockHandler.PARISTEEL_METAL.getStateFromMeta(3));
		worldIn.setBlockState(bp.add(i + 4, j + 3, k + 13), BlockHandler.PARISTEEL_METAL.getStateFromMeta(3));
		worldIn.setBlockState(bp.add(i + 4, j + 4, k + 2), BlockHandler.PARISTEEL_METAL.getStateFromMeta(3));
		worldIn.setBlockState(bp.add(i + 4, j + 4, k + 3), BlockHandler.PARISTEEL_METAL.getStateFromMeta(3));
		worldIn.setBlockState(bp.add(i + 4, j + 4, k + 4), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 4, j + 4, k + 5), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 4, j + 4, k + 6), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 4, j + 4, k + 7), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 4, j + 4, k + 8), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 4, j + 4, k + 9), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 4, j + 4, k + 10), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 4, j + 4, k + 11), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 4, j + 4, k + 12), BlockHandler.PARISTEEL_METAL.getStateFromMeta(3));
		worldIn.setBlockState(bp.add(i + 4, j + 4, k + 13), BlockHandler.PARISTEEL_METAL.getStateFromMeta(3));
		worldIn.setBlockState(bp.add(i + 4, j + 5, k + 4), BlockHandler.PARISTEEL_METAL.getStateFromMeta(15));
		worldIn.setBlockState(bp.add(i + 4, j + 5, k + 5), BlockHandler.PARISTEEL_METAL.getStateFromMeta(15));
		worldIn.setBlockState(bp.add(i + 4, j + 5, k + 6), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 4, j + 5, k + 9), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 4, j + 5, k + 10), BlockHandler.PARISTEEL_METAL.getStateFromMeta(15));
		worldIn.setBlockState(bp.add(i + 4, j + 5, k + 11), BlockHandler.PARISTEEL_METAL.getStateFromMeta(15));
		worldIn.setBlockState(bp.add(i + 4, j + 6, k + 5), BlockHandler.PARISTEEL_METAL.getStateFromMeta(15));
		worldIn.setBlockState(bp.add(i + 4, j + 6, k + 6), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 4, j + 6, k + 9), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 4, j + 6, k + 10), BlockHandler.PARISTEEL_METAL.getStateFromMeta(15));
		worldIn.setBlockState(bp.add(i + 4, j + 7, k + 6), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 4, j + 7, k + 7), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 4, j + 7, k + 8), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 4, j + 7, k + 9), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 5, j + 0, k + 3), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 5, j + 0, k + 4), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 5, j + 0, k + 5), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 5, j + 0, k + 6), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 5, j + 0, k + 7), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 5, j + 0, k + 8), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 5, j + 0, k + 9), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 5, j + 0, k + 10), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 5, j + 0, k + 11), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 5, j + 0, k + 12), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 5, j + 1, k + 2), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 5, j + 1, k + 13), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 5, j + 2, k + 2), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 5, j + 2, k + 13), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 5, j + 3, k + 2), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 5, j + 3, k + 13), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 5, j + 4, k + 2), BlockHandler.PARISTEEL_METAL.getStateFromMeta(3));
		worldIn.setBlockState(bp.add(i + 5, j + 4, k + 3), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 5, j + 4, k + 4), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 5, j + 4, k + 5), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 5, j + 4, k + 6), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 5, j + 4, k + 7), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 5, j + 4, k + 8), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 5, j + 4, k + 9), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 5, j + 4, k + 10), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 5, j + 4, k + 11), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 5, j + 4, k + 12), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 5, j + 4, k + 13), BlockHandler.PARISTEEL_METAL.getStateFromMeta(3));
		worldIn.setBlockState(bp.add(i + 5, j + 5, k + 3), BlockHandler.PARISTEEL_METAL.getStateFromMeta(15));
		worldIn.setBlockState(bp.add(i + 5, j + 5, k + 4), BlockHandler.PARISTEEL_METAL.getStateFromMeta(15));
		worldIn.setBlockState(bp.add(i + 5, j + 5, k + 11), BlockHandler.PARISTEEL_METAL.getStateFromMeta(15));
		worldIn.setBlockState(bp.add(i + 5, j + 5, k + 12), BlockHandler.PARISTEEL_METAL.getStateFromMeta(15));
		worldIn.setBlockState(bp.add(i + 5, j + 6, k + 4), BlockHandler.PARISTEEL_METAL.getStateFromMeta(15));
		worldIn.setBlockState(bp.add(i + 5, j + 6, k + 5), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 5, j + 6, k + 6), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 5, j + 6, k + 9), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 5, j + 6, k + 10), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 5, j + 6, k + 11), BlockHandler.PARISTEEL_METAL.getStateFromMeta(15));
		worldIn.setBlockState(bp.add(i + 5, j + 7, k + 4), BlockHandler.PARISTEEL_METAL.getStateFromMeta(15));
		worldIn.setBlockState(bp.add(i + 5, j + 7, k + 5), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 5, j + 7, k + 6), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 5, j + 7, k + 9), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 5, j + 7, k + 10), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 5, j + 7, k + 11), BlockHandler.PARISTEEL_METAL.getStateFromMeta(15));
		worldIn.setBlockState(bp.add(i + 5, j + 8, k + 7), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 5, j + 8, k + 8), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 6, j + 0, k + 3), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 6, j + 0, k + 4), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 6, j + 0, k + 5), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 6, j + 0, k + 6), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 6, j + 0, k + 7), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 6, j + 0, k + 8), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 6, j + 0, k + 9), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 6, j + 0, k + 10), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 6, j + 0, k + 11), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 6, j + 0, k + 12), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 6, j + 1, k + 2), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 6, j + 1, k + 13), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 6, j + 2, k + 2), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 6, j + 2, k + 13), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 6, j + 3, k + 2), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 6, j + 3, k + 13), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 6, j + 4, k + 2), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 6, j + 4, k + 3), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 6, j + 4, k + 4), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 6, j + 4, k + 5), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 6, j + 4, k + 6), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 6, j + 4, k + 7), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 6, j + 4, k + 8), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 6, j + 4, k + 9), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 6, j + 4, k + 10), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 6, j + 4, k + 11), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 6, j + 4, k + 12), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 6, j + 4, k + 13), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 6, j + 5, k + 3), BlockHandler.PARISTEEL_METAL.getStateFromMeta(15));
		worldIn.setBlockState(bp.add(i + 6, j + 5, k + 12), BlockHandler.PARISTEEL_METAL.getStateFromMeta(15));
		worldIn.setBlockState(bp.add(i + 6, j + 6, k + 3), BlockHandler.PARISTEEL_METAL.getStateFromMeta(15));
		worldIn.setBlockState(bp.add(i + 6, j + 6, k + 4), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 6, j + 6, k + 5), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 6, j + 6, k + 10), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 6, j + 6, k + 11), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 6, j + 6, k + 12), BlockHandler.PARISTEEL_METAL.getStateFromMeta(15));
		worldIn.setBlockState(bp.add(i + 6, j + 7, k + 4), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 6, j + 7, k + 5), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 6, j + 7, k + 10), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 6, j + 7, k + 11), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 6, j + 8, k + 6), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 6, j + 8, k + 7), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 6, j + 8, k + 8), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 6, j + 8, k + 9), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 7, j + 0, k + 2), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 7, j + 0, k + 3), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 7, j + 0, k + 4), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 7, j + 0, k + 5), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 7, j + 0, k + 6), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 7, j + 0, k + 7), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 7, j + 0, k + 8), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 7, j + 0, k + 9), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 7, j + 0, k + 10), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 7, j + 0, k + 11), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 7, j + 0, k + 12), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 7, j + 0, k + 13), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 7, j + 1, k + 1), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));

		setTileEntityBlock(worldIn, bp.add(i + 7, j + 1, k + 2), Blocks.CHEST.getDefaultState(), new TileEntityChest());
		setLockableLoot(worldIn, bp.add(i + 7, j + 1, k + 2), LootTableHandler.TERRAN_BUNKER);

		worldIn.setBlockState(bp.add(i + 7, j + 1, k + 11), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 7, j + 1, k + 14), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 7, j + 2, k + 1), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 7, j + 2, k + 11), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 7, j + 2, k + 14), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 7, j + 3, k + 1), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 7, j + 3, k + 11), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 7, j + 3, k + 14), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 7, j + 4, k + 1), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 7, j + 4, k + 2), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 7, j + 4, k + 3), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 7, j + 4, k + 4), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 7, j + 4, k + 5), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 7, j + 4, k + 6), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 7, j + 4, k + 7), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 7, j + 4, k + 8), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 7, j + 4, k + 9), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 7, j + 4, k + 10), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 7, j + 4, k + 11), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 7, j + 4, k + 12), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 7, j + 4, k + 13), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 7, j + 4, k + 14), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 7, j + 5, k + 2), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 7, j + 5, k + 3), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 7, j + 5, k + 12), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 7, j + 5, k + 13), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 7, j + 6, k + 3), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 7, j + 6, k + 4), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 7, j + 6, k + 11), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 7, j + 6, k + 12), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 7, j + 7, k + 3), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 7, j + 7, k + 4), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 7, j + 7, k + 11), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 7, j + 7, k + 12), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 7, j + 8, k + 5), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 7, j + 8, k + 6), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 7, j + 8, k + 7), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 7, j + 8, k + 8), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 7, j + 8, k + 9), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 7, j + 8, k + 10), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 8, j + 0, k + 1), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 8, j + 0, k + 2), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 8, j + 0, k + 3), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 8, j + 0, k + 4), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 8, j + 0, k + 5), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 8, j + 0, k + 6), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 8, j + 0, k + 7), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 8, j + 0, k + 8), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 8, j + 0, k + 9), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 8, j + 0, k + 10), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 8, j + 0, k + 11), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 8, j + 0, k + 12), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 8, j + 0, k + 13), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 8, j + 0, k + 14), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 8, j + 1, k + 0), BlockHandler.TERRAN_WARNING_TAPE.getDefaultState());
		worldIn.setBlockState(bp.add(i + 8, j + 1, k + 1), BlockHandler.PARISTEEL_METAL.getStateFromMeta(15));
		worldIn.setBlockState(bp.add(i + 8, j + 1, k + 2), BlockHandler.PARISTEEL_METAL.getStateFromMeta(15));
		worldIn.setBlockState(bp.add(i + 8, j + 1, k + 11), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 8, j + 1, k + 13), BlockHandler.PARISTEEL_METAL.getStateFromMeta(15));
		worldIn.setBlockState(bp.add(i + 8, j + 1, k + 14), BlockHandler.PARISTEEL_METAL.getStateFromMeta(15));
		worldIn.setBlockState(bp.add(i + 8, j + 1, k + 15), BlockHandler.TERRAN_WARNING_TAPE.getDefaultState());
		worldIn.setBlockState(bp.add(i + 8, j + 2, k + 2), BlockHandler.PARISTEEL_METAL.getStateFromMeta(15));
		worldIn.setBlockState(bp.add(i + 8, j + 2, k + 11), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 8, j + 2, k + 13), BlockHandler.PARISTEEL_METAL.getStateFromMeta(15));
		worldIn.setBlockState(bp.add(i + 8, j + 3, k + 1), BlockHandler.PARISTEEL_METAL.getStateFromMeta(15));
		worldIn.setBlockState(bp.add(i + 8, j + 3, k + 2), BlockHandler.PARISTEEL_METAL.getStateFromMeta(15));
		worldIn.setBlockState(bp.add(i + 8, j + 3, k + 11), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 8, j + 3, k + 13), BlockHandler.PARISTEEL_METAL.getStateFromMeta(15));
		worldIn.setBlockState(bp.add(i + 8, j + 3, k + 14), BlockHandler.PARISTEEL_METAL.getStateFromMeta(15));
		worldIn.setBlockState(bp.add(i + 8, j + 4, k + 2), BlockHandler.PARISTEEL_METAL.getStateFromMeta(15));
		worldIn.setBlockState(bp.add(i + 8, j + 4, k + 3), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 8, j + 4, k + 4), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 8, j + 4, k + 5), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 8, j + 4, k + 6), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 8, j + 4, k + 7), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 8, j + 4, k + 8), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 8, j + 4, k + 9), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 8, j + 4, k + 10), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 8, j + 4, k + 12), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 8, j + 4, k + 13), BlockHandler.PARISTEEL_METAL.getStateFromMeta(15));
		worldIn.setBlockState(bp.add(i + 8, j + 5, k + 2), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 8, j + 5, k + 13), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 8, j + 7, k + 3), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 8, j + 7, k + 12), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 8, j + 8, k + 4), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		generate2(worldIn, bp);
		return true;
	}

	public boolean generate2(World worldIn, BlockPos bp) {
		// Change k, i, or j to offset the structure
		int k = 0;
		int i = 0;
		int j = 0;
		worldIn.setBlockState(bp.add(i + 8, j + 8, k + 5), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 8, j + 8, k + 6), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 8, j + 8, k + 7), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 8, j + 8, k + 8), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 8, j + 8, k + 9), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 8, j + 8, k + 10), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 8, j + 8, k + 11), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 9, j + 0, k + 1), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 9, j + 0, k + 2), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 9, j + 0, k + 3), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 9, j + 0, k + 4), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 9, j + 0, k + 5), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 9, j + 0, k + 6), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 9, j + 0, k + 7), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 9, j + 0, k + 8), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 9, j + 0, k + 9), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 9, j + 0, k + 10), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 9, j + 0, k + 11), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 9, j + 0, k + 12), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 9, j + 0, k + 13), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 9, j + 0, k + 14), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 9, j + 1, k + 0), BlockHandler.TERRAN_WARNING_TAPE.getDefaultState());
		worldIn.setBlockState(bp.add(i + 9, j + 1, k + 1), BlockHandler.PARISTEEL_METAL.getStateFromMeta(15));
		worldIn.setBlockState(bp.add(i + 9, j + 1, k + 2), BlockHandler.PARISTEEL_METAL.getStateFromMeta(15));
		worldIn.setBlockState(bp.add(i + 9, j + 1, k + 11), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 9, j + 1, k + 13), BlockHandler.PARISTEEL_METAL.getStateFromMeta(15));
		worldIn.setBlockState(bp.add(i + 9, j + 1, k + 14), BlockHandler.PARISTEEL_METAL.getStateFromMeta(15));
		worldIn.setBlockState(bp.add(i + 9, j + 1, k + 15), BlockHandler.TERRAN_WARNING_TAPE.getDefaultState());
		worldIn.setBlockState(bp.add(i + 9, j + 2, k + 2), BlockHandler.PARISTEEL_METAL.getStateFromMeta(15));
		worldIn.setBlockState(bp.add(i + 9, j + 2, k + 11), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 9, j + 2, k + 13), BlockHandler.PARISTEEL_METAL.getStateFromMeta(15));
		worldIn.setBlockState(bp.add(i + 9, j + 3, k + 1), BlockHandler.PARISTEEL_METAL.getStateFromMeta(15));
		worldIn.setBlockState(bp.add(i + 9, j + 3, k + 2), BlockHandler.PARISTEEL_METAL.getStateFromMeta(15));
		worldIn.setBlockState(bp.add(i + 9, j + 3, k + 13), BlockHandler.PARISTEEL_METAL.getStateFromMeta(15));
		worldIn.setBlockState(bp.add(i + 9, j + 3, k + 14), BlockHandler.PARISTEEL_METAL.getStateFromMeta(15));
		worldIn.setBlockState(bp.add(i + 9, j + 4, k + 2), BlockHandler.PARISTEEL_METAL.getStateFromMeta(15));
		worldIn.setBlockState(bp.add(i + 9, j + 4, k + 3), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 9, j + 4, k + 4), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 9, j + 4, k + 5), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 9, j + 4, k + 6), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 9, j + 4, k + 7), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 9, j + 4, k + 8), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 9, j + 4, k + 9), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 9, j + 4, k + 10), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 9, j + 4, k + 12), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 9, j + 4, k + 13), BlockHandler.PARISTEEL_METAL.getStateFromMeta(15));
		worldIn.setBlockState(bp.add(i + 9, j + 5, k + 2), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 9, j + 5, k + 13), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 9, j + 7, k + 3), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 9, j + 7, k + 12), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 9, j + 8, k + 4), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 9, j + 8, k + 5), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 9, j + 8, k + 6), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 9, j + 8, k + 7), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 9, j + 8, k + 8), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 9, j + 8, k + 9), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 9, j + 8, k + 10), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 9, j + 8, k + 11), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 10, j + 0, k + 2), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 10, j + 0, k + 3), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 10, j + 0, k + 4), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 10, j + 0, k + 5), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 10, j + 0, k + 6), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 10, j + 0, k + 7), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 10, j + 0, k + 8), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 10, j + 0, k + 9), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 10, j + 0, k + 10), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 10, j + 0, k + 11), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 10, j + 0, k + 12), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 10, j + 0, k + 13), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 10, j + 1, k + 1), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 10, j + 1, k + 11), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));

		setTileEntityBlock(worldIn, bp.add(i + 10, j + 1, k + 13), Blocks.CHEST.getDefaultState(), new TileEntityChest());
		setLockableLoot(worldIn, bp.add(i + 10, j + 1, k + 13), LootTableHandler.TERRAN_BUNKER);

		worldIn.setBlockState(bp.add(i + 10, j + 1, k + 14), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 10, j + 2, k + 1), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 10, j + 2, k + 14), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 10, j + 3, k + 1), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 10, j + 3, k + 14), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 10, j + 4, k + 1), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 10, j + 4, k + 2), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 10, j + 4, k + 3), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 10, j + 4, k + 4), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 10, j + 4, k + 5), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 10, j + 4, k + 6), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 10, j + 4, k + 7), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 10, j + 4, k + 8), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 10, j + 4, k + 9), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 10, j + 4, k + 10), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 10, j + 4, k + 12), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 10, j + 4, k + 14), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 10, j + 5, k + 2), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 10, j + 5, k + 3), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 10, j + 5, k + 12), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 10, j + 5, k + 13), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 10, j + 6, k + 3), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 10, j + 6, k + 4), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 10, j + 6, k + 11), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 10, j + 6, k + 12), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 10, j + 7, k + 3), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 10, j + 7, k + 4), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 10, j + 7, k + 11), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 10, j + 7, k + 12), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 10, j + 8, k + 5), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 10, j + 8, k + 6), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 10, j + 8, k + 7), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 10, j + 8, k + 8), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 10, j + 8, k + 9), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 10, j + 8, k + 10), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 11, j + 0, k + 3), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 11, j + 0, k + 4), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 11, j + 0, k + 5), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 11, j + 0, k + 6), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 11, j + 0, k + 7), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 11, j + 0, k + 8), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 11, j + 0, k + 9), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 11, j + 0, k + 10), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 11, j + 0, k + 11), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 11, j + 0, k + 12), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 11, j + 1, k + 2), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 11, j + 1, k + 13), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 11, j + 2, k + 2), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 11, j + 2, k + 13), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 11, j + 3, k + 2), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 11, j + 3, k + 13), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 11, j + 4, k + 2), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 11, j + 4, k + 3), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 11, j + 4, k + 4), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 11, j + 4, k + 5), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 11, j + 4, k + 6), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 11, j + 4, k + 7), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 11, j + 4, k + 8), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 11, j + 4, k + 9), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 11, j + 4, k + 10), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 11, j + 4, k + 11), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 11, j + 4, k + 12), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 11, j + 4, k + 13), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 11, j + 5, k + 3), BlockHandler.PARISTEEL_METAL.getStateFromMeta(15));
		worldIn.setBlockState(bp.add(i + 11, j + 5, k + 12), BlockHandler.PARISTEEL_METAL.getStateFromMeta(15));
		worldIn.setBlockState(bp.add(i + 11, j + 6, k + 3), BlockHandler.PARISTEEL_METAL.getStateFromMeta(15));
		worldIn.setBlockState(bp.add(i + 11, j + 6, k + 4), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 11, j + 6, k + 5), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 11, j + 6, k + 10), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 11, j + 6, k + 11), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 11, j + 6, k + 12), BlockHandler.PARISTEEL_METAL.getStateFromMeta(15));
		worldIn.setBlockState(bp.add(i + 11, j + 7, k + 4), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 11, j + 7, k + 5), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 11, j + 7, k + 10), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 11, j + 7, k + 11), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 11, j + 8, k + 6), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 11, j + 8, k + 7), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 11, j + 8, k + 8), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 11, j + 8, k + 9), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 12, j + 0, k + 3), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 12, j + 0, k + 4), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 12, j + 0, k + 5), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 12, j + 0, k + 6), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 12, j + 0, k + 7), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 12, j + 0, k + 8), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 12, j + 0, k + 9), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 12, j + 0, k + 10), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 12, j + 0, k + 11), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 12, j + 0, k + 12), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 12, j + 1, k + 2), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 12, j + 1, k + 13), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 12, j + 2, k + 2), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 12, j + 2, k + 13), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 12, j + 3, k + 2), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 12, j + 3, k + 13), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 12, j + 4, k + 2), BlockHandler.PARISTEEL_METAL.getStateFromMeta(3));
		worldIn.setBlockState(bp.add(i + 12, j + 4, k + 3), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 12, j + 4, k + 4), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 12, j + 4, k + 5), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 12, j + 4, k + 6), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 12, j + 4, k + 7), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 12, j + 4, k + 8), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 12, j + 4, k + 9), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 12, j + 4, k + 10), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 12, j + 4, k + 11), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 12, j + 4, k + 12), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 12, j + 4, k + 13), BlockHandler.PARISTEEL_METAL.getStateFromMeta(3));
		worldIn.setBlockState(bp.add(i + 12, j + 5, k + 3), BlockHandler.PARISTEEL_METAL.getStateFromMeta(15));
		worldIn.setBlockState(bp.add(i + 12, j + 5, k + 4), BlockHandler.PARISTEEL_METAL.getStateFromMeta(15));
		worldIn.setBlockState(bp.add(i + 12, j + 5, k + 11), BlockHandler.PARISTEEL_METAL.getStateFromMeta(15));
		worldIn.setBlockState(bp.add(i + 12, j + 5, k + 12), BlockHandler.PARISTEEL_METAL.getStateFromMeta(15));
		worldIn.setBlockState(bp.add(i + 12, j + 6, k + 4), BlockHandler.PARISTEEL_METAL.getStateFromMeta(15));
		worldIn.setBlockState(bp.add(i + 12, j + 6, k + 5), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 12, j + 6, k + 6), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 12, j + 6, k + 9), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 12, j + 6, k + 10), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 12, j + 6, k + 11), BlockHandler.PARISTEEL_METAL.getStateFromMeta(15));
		worldIn.setBlockState(bp.add(i + 12, j + 7, k + 4), BlockHandler.PARISTEEL_METAL.getStateFromMeta(15));
		worldIn.setBlockState(bp.add(i + 12, j + 7, k + 5), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 12, j + 7, k + 6), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 12, j + 7, k + 9), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 12, j + 7, k + 10), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 12, j + 7, k + 11), BlockHandler.PARISTEEL_METAL.getStateFromMeta(15));
		worldIn.setBlockState(bp.add(i + 12, j + 8, k + 7), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 12, j + 8, k + 8), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 13, j + 0, k + 3), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 13, j + 0, k + 4), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 13, j + 0, k + 5), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 13, j + 0, k + 6), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 13, j + 0, k + 7), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 13, j + 0, k + 8), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 13, j + 0, k + 9), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 13, j + 0, k + 10), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 13, j + 0, k + 11), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 13, j + 0, k + 12), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 13, j + 1, k + 2), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));

		setTileEntityBlock(worldIn, bp.add(i + 13, j + 1, k + 3), Blocks.CHEST.getDefaultState(), new TileEntityChest());
		setLockableLoot(worldIn, bp.add(i + 13, j + 1, k + 3), LootTableHandler.TERRAN_BUNKER);

		worldIn.setBlockState(bp.add(i + 13, j + 1, k + 13), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 13, j + 2, k + 2), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 13, j + 2, k + 13), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 13, j + 3, k + 2), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 13, j + 3, k + 13), BlockHandler.PARISTEEL_METAL.getStateFromMeta(3));
		worldIn.setBlockState(bp.add(i + 13, j + 4, k + 2), BlockHandler.PARISTEEL_METAL.getStateFromMeta(3));
		worldIn.setBlockState(bp.add(i + 13, j + 4, k + 3), BlockHandler.PARISTEEL_METAL.getStateFromMeta(3));
		worldIn.setBlockState(bp.add(i + 13, j + 4, k + 4), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 13, j + 4, k + 5), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 13, j + 4, k + 6), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 13, j + 4, k + 7), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 13, j + 4, k + 8), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 13, j + 4, k + 10), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 13, j + 4, k + 11), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 13, j + 4, k + 12), BlockHandler.PARISTEEL_METAL.getStateFromMeta(3));
		worldIn.setBlockState(bp.add(i + 13, j + 4, k + 13), BlockHandler.PARISTEEL_METAL.getStateFromMeta(3));
		worldIn.setBlockState(bp.add(i + 13, j + 5, k + 4), BlockHandler.PARISTEEL_METAL.getStateFromMeta(15));
		worldIn.setBlockState(bp.add(i + 13, j + 5, k + 5), BlockHandler.PARISTEEL_METAL.getStateFromMeta(15));
		worldIn.setBlockState(bp.add(i + 13, j + 5, k + 6), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 13, j + 5, k + 9), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 13, j + 5, k + 10), BlockHandler.PARISTEEL_METAL.getStateFromMeta(15));
		worldIn.setBlockState(bp.add(i + 13, j + 5, k + 11), BlockHandler.PARISTEEL_METAL.getStateFromMeta(15));
		worldIn.setBlockState(bp.add(i + 13, j + 6, k + 5), BlockHandler.PARISTEEL_METAL.getStateFromMeta(15));
		worldIn.setBlockState(bp.add(i + 13, j + 6, k + 6), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 13, j + 6, k + 9), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 13, j + 6, k + 10), BlockHandler.PARISTEEL_METAL.getStateFromMeta(15));
		worldIn.setBlockState(bp.add(i + 13, j + 7, k + 6), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 13, j + 7, k + 7), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 13, j + 7, k + 8), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 13, j + 7, k + 9), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 14, j + 0, k + 6), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 14, j + 0, k + 7), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 14, j + 0, k + 8), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 14, j + 0, k + 9), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 14, j + 1, k + 3), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 14, j + 1, k + 4), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 14, j + 1, k + 5), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 14, j + 1, k + 10), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 14, j + 1, k + 11), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 14, j + 1, k + 12), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 14, j + 2, k + 2), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 14, j + 2, k + 3), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 14, j + 2, k + 4), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 14, j + 2, k + 5), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 14, j + 2, k + 10), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 14, j + 2, k + 11), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 14, j + 2, k + 12), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 14, j + 2, k + 13), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 14, j + 3, k + 2), BlockHandler.PARISTEEL_METAL.getStateFromMeta(3));
		worldIn.setBlockState(bp.add(i + 14, j + 3, k + 3), BlockHandler.PARISTEEL_METAL.getStateFromMeta(3));
		worldIn.setBlockState(bp.add(i + 14, j + 3, k + 4), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 14, j + 3, k + 5), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 14, j + 3, k + 10), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 14, j + 3, k + 11), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 14, j + 3, k + 12), BlockHandler.PARISTEEL_METAL.getStateFromMeta(3));
		worldIn.setBlockState(bp.add(i + 14, j + 3, k + 13), BlockHandler.PARISTEEL_METAL.getStateFromMeta(3));
		worldIn.setBlockState(bp.add(i + 14, j + 4, k + 3), BlockHandler.PARISTEEL_METAL.getStateFromMeta(3));
		worldIn.setBlockState(bp.add(i + 14, j + 4, k + 4), BlockHandler.PARISTEEL_METAL.getStateFromMeta(3));
		worldIn.setBlockState(bp.add(i + 14, j + 4, k + 5), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 14, j + 4, k + 6), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 14, j + 4, k + 7), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 14, j + 4, k + 8), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 14, j + 4, k + 9), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 14, j + 4, k + 10), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 14, j + 4, k + 11), BlockHandler.PARISTEEL_METAL.getStateFromMeta(3));
		worldIn.setBlockState(bp.add(i + 14, j + 4, k + 12), BlockHandler.PARISTEEL_METAL.getStateFromMeta(3));
		worldIn.setBlockState(bp.add(i + 14, j + 5, k + 6), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 14, j + 5, k + 7), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 14, j + 5, k + 8), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 14, j + 5, k + 9), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 15, j + 0, k + 7), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 15, j + 0, k + 8), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 15, j + 1, k + 6), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 15, j + 1, k + 9), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 15, j + 2, k + 6), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 15, j + 2, k + 9), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 15, j + 3, k + 6), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 15, j + 3, k + 9), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 15, j + 4, k + 6), BlockHandler.PARISTEEL_METAL.getStateFromMeta(15));
		worldIn.setBlockState(bp.add(i + 15, j + 4, k + 9), BlockHandler.PARISTEEL_METAL.getStateFromMeta(15));
		worldIn.setBlockState(bp.add(i + 16, j + 0, k + 7), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 16, j + 0, k + 8), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 16, j + 1, k + 6), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 16, j + 1, k + 9), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 16, j + 2, k + 6), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 16, j + 2, k + 9), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 16, j + 3, k + 6), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 16, j + 3, k + 9), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 16, j + 4, k + 6), BlockHandler.PARISTEEL_METAL.getStateFromMeta(15));
		worldIn.setBlockState(bp.add(i + 16, j + 4, k + 9), BlockHandler.PARISTEEL_METAL.getStateFromMeta(15));
		worldIn.setBlockState(bp.add(i + 17, j + 0, k + 7), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 17, j + 0, k + 8), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 17, j + 1, k + 7), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 17, j + 1, k + 8), BlockHandler.NEOSTEEL_METAL.getStateFromMeta(1));
		worldIn.setBlockState(bp.add(i + 17, j + 1, k + 9), BlockHandler.PARISTEEL_METAL.getStateFromMeta(5));
		worldIn.setBlockState(bp.add(i + 17, j + 2, k + 6), BlockHandler.PARISTEEL_METAL.getStateFromMeta(15));
		worldIn.setBlockState(bp.add(i + 17, j + 2, k + 9), BlockHandler.PARISTEEL_METAL.getStateFromMeta(15));
		worldIn.setBlockState(bp.add(i + 17, j + 3, k + 6), BlockHandler.PARISTEEL_METAL.getStateFromMeta(15));
		worldIn.setBlockState(bp.add(i + 17, j + 3, k + 9), BlockHandler.PARISTEEL_METAL.getStateFromMeta(15));
		return true;
	}

	protected Block[] GetValidSpawnBlocks() {
		return new Block[] { Blocks.GRASS, Blocks.STONE, Blocks.DIRT, Blocks.SAND, BlockHandler.CITY_STONE_KORHAL };
	}

	public boolean LocationIsValidSpawn(World world, BlockPos pos) {
		Block checkBlock = world.getBlockState(pos).getBlock();
		Material m = checkBlock.getBlockState().getBaseState().getMaterial();
		Block blockAbove = world.getBlockState(pos.up()).getBlock();
		Block blockBelow = world.getBlockState(pos.down()).getBlock();
		for (Block i : GetValidSpawnBlocks()) {
			if (blockAbove != Blocks.AIR) {
				return false;
			}
			if (checkBlock == i) {
				return true;
			} else if (checkBlock == Blocks.SNOW_LAYER && blockBelow == i) {
				return true;
			} else if (m == Material.PLANTS && blockBelow == i) {
				world.getBlockState(pos).getMaterial();
				return true;
			}
		}
		return false;
	}
}