package io.github.scmcmod.enums;

public enum EnumTypeAttributes
{
	AIR, ARMORED, BIOLOGICAL, DETECTOR, GROUND, HEROIC, HOVER, LIGHT, MASSIVE, MECHANICAL, OTHER, PSIONIC, ROBOTIC, SUMMONED, PROJECTILE, CRITTER, INVISIBLE, DETECTED
}