package com.hypeirochus.scmc.client.renderer;

import com.hypeirochus.scmc.Starcraft;

import net.minecraft.util.ResourceLocation;

public class Resources {

	public static final String ARTOSILOPE_BASE = Starcraft.RL_BASE + "textures/entity/artosilope_base.png";
	public static final String BRAKK_BASE = Starcraft.RL_BASE + "textures/entity/brakk_base.png";
	public static final String BRAKK_GLOW_DYNAMIC = Starcraft.RL_BASE + "textures/entity/brakk_glow_dynamic.png";
	public static final String BRAKK_OVERLAY = Starcraft.RL_BASE + "textures/entity/brakk_overlay.png";
	public static final String BROODLING_BASE = Starcraft.RL_BASE + "textures/entity/broodling_base.png";
	public static final String BROODLING_OVERLAY = Starcraft.RL_BASE + "textures/entity/broodling_overlay.png";
	public static final String BROODMOTHER_BASE = Starcraft.RL_BASE + "textures/entity/broodmother_base.png";
	public static final String BROODMOTHER_GLOW_STATIC = Starcraft.RL_BASE + "textures/entity/broodmother_glow_static.png";
	public static final String BROODMOTHER_GLOW_DYNAMIC = Starcraft.RL_BASE + "textures/entity/broodmother_glow_dynamic.png";
	public static final String BROODMOTHER_OVERLAY = Starcraft.RL_BASE + "textures/entity/broodmother_overlay.png";
	public static final String BRUTALISK_BASE = Starcraft.RL_BASE + "textures/entity/brutalisk_base.png";
	public static final String BRUTALISK_OVERLAY = Starcraft.RL_BASE + "textures/entity/brutalisk_overlay.png";
	public static final String BULLET_C14 = Starcraft.RL_BASE + "textures/entity/bullet.png";
	public static final String CIVILIAN = Starcraft.RL_BASE + "textures/entity/civilian.png";
	public static final String DARKPROBE_BASE = Starcraft.RL_BASE + "textures/entity/darkprobe_base.png";
	public static final String DARKPROBE_GLOW_DYNAMIC = Starcraft.RL_BASE + "textures/entity/darkprobe_glow_dynamic.png";
	public static final String DARKPROBE_OVERLAY = Starcraft.RL_BASE + "textures/entity/darkprobe_overlay.png";
	public static final String DARKTEMPLAR_BASE = Starcraft.RL_BASE + "textures/entity/darktemplar_base.png";
	public static final String DARKTEMPLAR_GLOW_STATIC = Starcraft.RL_BASE + "textures/entity/darktemplar_glow_static.png";
	public static final String DARKTEMPLAR_OVERLAY = Starcraft.RL_BASE + "textures/entity/darktemplar_overlay.png";
	public static final String HYDRALISK_BASE = Starcraft.RL_BASE + "textures/entity/hydralisk_base.png";
	public static final String HYDRALISK_GLOW_STATIC = Starcraft.RL_BASE + "textures/entity/hydralisk_glow_static.png";
	public static final String HYDRALISK_OVERLAY = Starcraft.RL_BASE + "textures/entity/hydralisk_overlay.png";
	public static final String HYDRALISK_SPIKE = Starcraft.RL_BASE + "textures/entity/hydraliskspike.png";
	public static final String HYDRALISKPRIMAL_BASE = Starcraft.RL_BASE + "textures/entity/hydraliskprimal_base.png";
	public static final String HYDRALISKPRIMAL_OVERLAY = Starcraft.RL_BASE + "textures/entity/hydraliskprimal_overlay.png";
	public static final String HYDRALISKPRIMALDEHAKA_BASE = Starcraft.RL_BASE + "textures/entity/hydraliskprimaldehaka_base.png";
	public static final String HYDRALISKPRIMALDEHAKA_GLOW_STATIC = Starcraft.RL_BASE + "textures/entity/hydraliskprimaldehaka_glow_static.png";
	public static final String INFESTED_CIVILIAN = Starcraft.RL_BASE + "textures/entity/infestedcivilian.png";
	public static final String JIMRAYNOR_BASE = Starcraft.RL_BASE + "textures/entity/jimraynor_base.png";
	public static final String KAKARU = Starcraft.RL_BASE + "textures/entity/kakaru.png";
	public static final String LARVA_BASE = Starcraft.RL_BASE + "textures/entity/larva_base.png";
	public static final String LARVA_GLOW_STATIC = Starcraft.RL_BASE + "textures/entity/larva_glow_static.png";
	public static final String LARVA_OVERLAY = Starcraft.RL_BASE + "textures/entity/larva_overlay.png";
	public static final String LARVA_COCOON_BASE = Starcraft.RL_BASE + "textures/entity/larvacocoon_base.png";
	public static final String LARVA_COCOON_OVERLAY = Starcraft.RL_BASE + "textures/entity/larvacocoon_overlay.png";
	public static final String MARINE_BASE = Starcraft.RL_BASE + "textures/entity/marine/marine_base.png";
	public static final String MARINE_OVERLAY = Starcraft.RL_BASE + "textures/entity/marine/marine_overlay.png";
	public static final String MUTALISK_BASE = Starcraft.RL_BASE + "textures/entity/mutalisk_base.png";
	public static final String MUTALISK_GLOW_STATIC = Starcraft.RL_BASE + "textures/entity/mutalisk_glow_static.png";
	public static final String MUTALISK_OVERLAY = Starcraft.RL_BASE + "textures/entity/mutalisk_overlay.png";
	public static final String MUTALISKBROODLORD_BASE = Starcraft.RL_BASE + "textures/entity/mutaliskbroodlord_base.png";
	public static final String MUTALISKBROODLORD_OVERLAY = Starcraft.RL_BASE + "textures/entity/mutaliskbroodlord_overlay.png";
	public static final String MUTALISKPRIMAL_BASE = Starcraft.RL_BASE + "textures/entity/mutaliskprimal_base.png";
	public static final String MUTALISKPRIMAL_OVERLAY = Starcraft.RL_BASE + "textures/entity/mutaliskprimal_overlay.png";
	public static final String MUTALISKPRIMALDEHAKA_BASE = Starcraft.RL_BASE + "textures/entity/mutaliskprimaldehaka_base.png";
	public static final String MUTALISKPRIMALDEHAKA_GLOW_STATIC = Starcraft.RL_BASE + "textures/entity/mutaliskprimaldehaka_glow_static.png";
	public static final String MUTALISKPRIMALDEHAKA_OVERLAY = Starcraft.RL_BASE + "textures/entity/mutaliskprimaldehaka_overlay.png";
	public static final String MUTALISKVIPER_BASE = Starcraft.RL_BASE + "textures/entity/mutaliskviper_base.png";
	public static final String MUTALISKVIPER_OVERLAY = Starcraft.RL_BASE + "textures/entity/mutaliskviper_overlay.png";
	public static final String PREAVER_BASE = Starcraft.RL_BASE + "textures/entity/preaver_base.png";
	public static final String PREAVER_GLOW_DYNAMIC = Starcraft.RL_BASE + "textures/entity/preaver_glow_dynamic.png";
	public static final String PREAVER_OVERLAY = Starcraft.RL_BASE + "textures/entity/preaver_overlay.png";
	public static final String PREDATOR_BASE = Starcraft.RL_BASE + "textures/entity/predator_base.png";
	public static final String PREDATOR_GLOW_DYNAMIC = Starcraft.RL_BASE + "textures/entity/predator_glow_dynamic.png";
	public static final String PREDATOR_GLOW_STATIC = Starcraft.RL_BASE + "textures/entity/predator_glow_static.png";
	public static final String PREDATOR_OVERLAY = Starcraft.RL_BASE + "textures/entity/predator_overlay.png";
	public static final String PROBE_BASE = Starcraft.RL_BASE + "textures/entity/probe_base.png";
	public static final String PROBE_GLOW_DYNAMIC = Starcraft.RL_BASE + "textures/entity/probe_glow_dynamic.png";
	public static final String PROBE_OVERLAY = Starcraft.RL_BASE + "textures/entity/probe_overlay.png";
	public static final String QUEEN_BASE = Starcraft.RL_BASE + "textures/entity/queen_base.png";
	public static final String QUEEN_GLOW_STATIC = Starcraft.RL_BASE + "textures/entity/queen_glow_static.png";
	public static final String QUEEN_OVERLAY = Starcraft.RL_BASE + "textures/entity/queen_overlay.png";
	public static final String SCARAB_LAYER = Starcraft.RL_BASE + "textures/entity/scarab_layer.png";
	public static final String SCARAB = Starcraft.RL_BASE + "textures/entity/scarab.png";
	public static final String TASTELOPE_BASE = Starcraft.RL_BASE + "textures/entity/tastelope_base.png";
	public static final String TASTELOPE_GLOW_STATIC = Starcraft.RL_BASE + "textures/entity/tastelope_glow_static.png";
	public static final String TYRANNOZOR_BASE = Starcraft.RL_BASE + "textures/entity/tyrannozor_base.png";
	public static final String TYRANNOZOR_GLOW_DYNAMIC = Starcraft.RL_BASE + "textures/entity/tyrannozor_glow_dynamic.png";
	public static final String TYRANNOZOR_OVERLAY = Starcraft.RL_BASE + "textures/entity/tyrannozor_overlay.png";
	public static final String TYRANNOZORDEHAKA_BASE = Starcraft.RL_BASE + "textures/entity/tyrannozordehaka_base.png";
	public static final String TYRANNOZORDEHAKA_GLOW_DYNAMIC = Starcraft.RL_BASE + "textures/entity/tyrannozordehaka_glow_dynamic.png";
	public static final String TYRANNOZORDEHAKA_GLOW_STATIC = Starcraft.RL_BASE + "textures/entity/tyrannozordehaka_glow_static.png";
	public static final String TYRANNOZORDEHAKA_OVERLAY = Starcraft.RL_BASE + "textures/entity/tyrannozordehaka_overlay.png";
	public static final String URSADON_BASE = Starcraft.RL_BASE + "textures/entity/ursadon_base.png";
	public static final String URSADON_MATRIARCH_BASE = Starcraft.RL_BASE + "textures/entity/ursadon_matriarch_base.png";
	public static final String VOID_PROBE_BASE = Starcraft.RL_BASE + "textures/entity/voidprobe_base.png";
	public static final String VOID_PROBE_GLOW_DYNAMIC = Starcraft.RL_BASE + "textures/entity/voidprobe_glow_dynamic.png";
	public static final String VOID_PROBE_OVERLAY = Starcraft.RL_BASE + "textures/entity/voidprobe_overlay.png";
	public static final String ZEALOT_BASE = Starcraft.RL_BASE + "textures/entity/zealot_base.png";
	public static final String ZEALOT_GLOW_DYNAMIC = Starcraft.RL_BASE + "textures/entity/zealot_glow_dynamic.png";
	public static final String ZEALOT_GLOW_STATIC = Starcraft.RL_BASE + "textures/entity/zealot_glow_static.png";
	public static final String ZEALOT_OVERLAY = Starcraft.RL_BASE + "textures/entity/zealot_overlay.png";
	public static final String ZERATUL_BASE = Starcraft.RL_BASE + "textures/entity/zeratul_base.png";
	public static final String ZERATUL_GLOW_STATIC = Starcraft.RL_BASE + "textures/entity/zeratul_glow_static.png";
	public static final String ZERATUL_OVERLAY = Starcraft.RL_BASE + "textures/entity/zeratul_overlay.png";
	public static final String ZERGLING_BASE = Starcraft.RL_BASE + "textures/entity/zergling_base.png";
	public static final String ZERGLING_GLOW_STATIC = Starcraft.RL_BASE + "textures/entity/zergling_glow_static.png";
	public static final String ZERGLING_OVERLAY = Starcraft.RL_BASE + "textures/entity/zergling_overlay.png";
	public static final String ZERGLINGBOOST_BASE = Starcraft.RL_BASE + "textures/entity/zerglingboost_base.png";
	public static final String ZERGLINGPRIMAL_GLOW_DYNAMIC = Starcraft.RL_BASE + "textures/entity/zerglingprimal_glow_dynamic.png";
	public static final String ZERGLINGPRIMAL1_BASE = Starcraft.RL_BASE + "textures/entity/zerglingprimal1_base.png";
	public static final String ZERGLINGPRIMAL1_OVERLAY = Starcraft.RL_BASE + "textures/entity/zerglingprimal1_overlay.png";
	public static final String ZERGLINGPRIMAL2_BASE = Starcraft.RL_BASE + "textures/entity/zerglingprimal2_base.png";
	public static final String ZERGLINGPRIMAL2_OVERLAY = Starcraft.RL_BASE + "textures/entity/zerglingprimal2_overlay.png";
	public static final String ZERGLINGPRIMAL3_BASE = Starcraft.RL_BASE + "textures/entity/zerglingprimal3_base.png";
	public static final String ZERGLINGPRIMAL3_OVERLAY = Starcraft.RL_BASE + "textures/entity/zerglingprimal3_overlay.png";
	public static final String ZERGLINGPRIMALDEHAKABOOST_BASE = Starcraft.RL_BASE + "textures/entity/zerglingprimaldehakaboost_base.png";
	public static final String ZERGLINGPRIMALDEHAKA_BASE = Starcraft.RL_BASE + "textures/entity/zerglingprimaldehaka_base.png";
	public static final String ZERGLINGPRIMALDEHAKA_OVERLAY = Starcraft.RL_BASE + "textures/entity/zerglingprimaldehaka_overlay.png";
	public static final String ZERGLINGPRIMALDEHAKA_GLOW_STATIC = Starcraft.RL_BASE + "textures/entity/zerglingprimaldehaka_glow_static.png";
	public static final String ZERGLINGRAPTOR_BASE = Starcraft.RL_BASE + "textures/entity/zerglingraptor_base.png";
	public static final String ZERGLINGSWARMLING_BASE = Starcraft.RL_BASE + "textures/entity/zerglingswarmling_base.png";
	public static final String ZERGLINGSWARMLING_GLOW_STATIC = Starcraft.RL_BASE + "textures/entity/zerglingswarmling_glow_static.png";

	public static final ResourceLocation KALDIR_BRAMBLES_TEXTURE = new ResourceLocation(Starcraft.RL_BASE + "textures/models/block/kaldir_brambles.png");
	public static final ResourceLocation SHAKURAS_PALM_TEXTURE = new ResourceLocation(Starcraft.RL_BASE + "textures/models/block/shakuras_brambles.png");
	public static final ResourceLocation ZERUS_PALM_TEXTURE = new ResourceLocation(Starcraft.RL_BASE + "textures/models/block/zerus_brambles.png");

}